using System;
using Microsoft.OData.Client;

namespace Alethic.Epicor.Kinetic.Client;

/// <summary>
/// Creates Microsoft.OData.Client contexts for Kinetic. Every business object service is its own OData service root
/// with its own <c>$metadata</c>, so one context is created per service. Contexts send their requests through the
/// authenticated Kinetic HttpClient pipeline.
/// </summary>
public interface IKineticODataContextFactory
{

    /// <summary>
    /// Context rooted at <c>api/v2/odata/{company}/{service}/</c>, for example <c>Erp.BO.CustomerSvc</c>.
    /// </summary>
    DataServiceContext ForService(string service);

    /// <summary>
    /// Context rooted at <c>api/v2/odata/{company}/BaqSvc/{baqId}/</c>. The entity set is <c>Data</c>.
    /// </summary>
    DataServiceContext ForBaq(string baqId);

    /// <summary>
    /// Absolute service root for a business object service, for constructing generated containers.
    /// </summary>
    Uri ServiceRoot(string service);

    /// <summary>
    /// Routes any context, including a container generated by OData Connected Service, through the authenticated
    /// Kinetic pipeline. Returns the same instance for chaining.
    /// </summary>
    TContext Configure<TContext>(TContext context)
        where TContext : DataServiceContext;

}
